name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        run: pipx run build

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          path: ./dist/*
